version: "3.8"

services:
  php:
    container_name: php
    build:
      context: ./symfony-alpine-docker/
      dockerfile: Dockerfile
    volumes:
      - var:/var/www/html/var
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - ../../app:/var/www/html/
    ports:
      - "${APACHE_HTTP_PORT}:80"
    env_file:
      - .env
    networks:
      - app-network

  db:
    container_name: ${DB_HOST}
    image: postgres:${DB_VERS}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
        - ${DB_EXT_PORT}:${DB_PORT}
    networks:
      - app-network

  rabbitmq:
    container_name: ${RQ_HOST}
    image: rabbitmq:${RQ_VERS}
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RQ_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RQ_PASS}
    ports:
      - "${RQ_HTTP_PORT}:15672"
      - "${RQ_AMQP_PORT}:5672"
    env_file:
      - .env
    networks:
      - app-network

  mailhog:
    container_name: ${MH_HOST}
    image: mailhog/mailhog
    ports:
      - ${MH_HTTP_PORT}:8025
      - ${MH_SMTP_PORT}:1025
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  var:
  vendor:
  node_modules: