version: "3.8"

services:
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ../../app:/var/www:delegated
    ports:
      - "${CUSTOM_PHP_PORT}:9000"
      - "${CUSTOM_WEBSERVER_PORT:-8181}:80"
    env_file:
      - .env
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-13}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
        - ${CUSTOM_POSTGRES_PORT:-15432}:5432
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${CUSTOM_RABBITMQ_MANAGER_PORT}:15672"
      - "${CUSTOM_RABBITMQ_PORT}:5672"
    env_file:
      - .env
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - ${CUSTOM_UI_PORT}:8025
      - ${CUSTOM_SMTP_PORT}:1025
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge