version: "3.8"

services:
  php:
    build:
      context: ./symfony-alpine-docker/
      dockerfile: Dockerfile
      args:
        AMQP_ENABLED: ${AMQP_ENABLED}
        NODEJS_PACKAGE_MANAGER: ${NODEJS_PACKAGE_MANAGER}
    container_name: php
    volumes:
      - var:/var/www/html/var
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - ../../app:/var/www/html/
    ports:
      - "${APACHE_EXTERNAL_PORT:-8181}:80"
    env_file:
      - .env
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-13}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
        - ${CUSTOM_POSTGRES_PORT:-15432}:5432
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${CUSTOM_RABBITMQ_MANAGER_PORT}:15672"
      - "${CUSTOM_RABBITMQ_PORT}:5672"
    env_file:
      - .env
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - ${CUSTOM_UI_PORT}:8025
      - ${CUSTOM_SMTP_PORT}:1025
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  var:
  vendor:
  node_modules: